# Generated by Django 4.2.1 on 2023-05-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
